all: calc.c branch.c loop.c
	gcc -o branch branch.c
	gcc -o loop loop.c
	gcc -o calc calc.c

calc: calc.c
	gcc -o calc calc.c

branch: branch.c
	gcc -o branch branch.c

loop: loop.c
	gcc -o loop loop.c

