all: loop.java branch.java calc.java
	javac loop.java branch.java calc.java

loop: loop.java
	javac loop.java

branch: branch.java
	javac branch.java

calc: calc.java
	javac calc.java

clean:
	rm *.class
